manifest:
  defaults:
    remote: zephyrproject-rtos

  remotes:
    - name: zephyrproject-rtos
      url-base: https://github.com/zephyrproject-rtos

  # Please add items below based on alphabetical order
  projects:
    - name: zephyr
      revision: v4.2.0
      remote: zephyrproject-rtos
      import:
        name-allowlist:
          - cmsis_6
          - hal_nordic

  self:
    path: app
